export { default as Nav } from './publics/Nav/Nav'
export { default as Box } from './Main/Box/Box'
export { default as Title } from './Main/Title/Title'
export { default as Career } from './Main/Career/Career'
export { default as Description } from './Main/Description/Description'
export { default as Link } from './Main/Link/Link'