name: deploy app
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code #get repo file
        uses: actions/checkout@master
        with:
          path: portfolio

      - name: git config
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"

      - name: install key
        env:
          GH_ACTION_DEPLOY_KEY: ${{ secrets.GH_ACTION_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh/
          echo "$GH_ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: clone data
        run: |
          cd ..
          git clone https://github.com/seo2im/portfolio.git portfolio
            
      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
              ${{ runner.OS }}-build-
              ${{ runner.OS }}-

      - name: npm install #set dependency
        run: npm install

      - name: npm build #building react app
        run: npm run buil
        
      - name: push
        run: |
          git add .
          git commit -m "feat:deployment"
          git push origin master

