name: deploy app
on: 
  push:
    branches:
      - master
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout code #get repo file
        uses: actions/checkout@master
        with:
          path: portfolio
      
      - name: checkout node
        uses: actions/setup-node@master
        with:
          node-version: 12.18.3

      - name: npm install #set dependency
        run: |
          cd portfolio
          npm install
          npm audit fix
          npm run build

      - name: push
        env:
          USER_NAME: ${{ github.event.pusher.name }}
          USER_EMAIL: ${{ github.event.pusher.email }}
        run: |
          git clone -b deployment --single-branch https://github.com/seo2im/portfolio.git deployment
          rm -rf ./deployment/*
          mv ./portfolio/* ./deployment
          cd deployment
          git config --global user.email "$USER_EMAIL"
          git config --global user.name "$USER_NAME"
          git add .
          git commit -m "deploy: deployment"
          git push origin deployment

